### ISSUE TITLE
Strange results with a very high coverage

### ISSUE THREAD

**Issue by e-sollier** [epi2me-labs/modbam2bed#10]
Hello,

Thanks for providing this tool.
It works as expected when I apply it to a human whole genome sequencing sample with ~30x coverage. 
However, I recently applied it to a sample consisting of double stranded 897bp DNA sequences, where the CpG sites are either fully methylated, fully hydroxymethylated or fully unmethylated (https://www.zymoresearch.de/products/5-methylcytosine-5-hydroxymethylcytosine-dna-standard-set). We have several million reads in the BAM files, for a 897bp sequence, so the coverage should be very high. Surprisingly, in the bed file that I get from modbam2bed, the coverage does not go beyond 9000. In addition, the BAM files contain as many reads aligned in forward and reverse orientation, whereas the bed file has much lower coverage on the - strand than on the + strand. See below the output of modbam2bed for 2 different samples:

<details>
<summary>Unmethylated data</summary>

seq1    38      39      5mC     730     +       38      39      0,0,0   8038    3.75
seq1    49      50      5mC     691     +       49      50      0,0,0   8049    5.74
seq1    54      55      5mC     779     +       54      55      0,0,0   8054    5.17
seq1    57      58      5mC     752     +       57      58      0,0,0   8057    6.05
seq1    75      76      5mC     744     +       75      76      0,0,0   8075    3.21
seq1    106     107     5mC     608     +       106     107     0,0,0   8106    4.80
seq1    116     117     5mC     432     +       116     117     0,0,0   8116    6.33
seq1    122     123     5mC     667     +       122     123     0,0,0   8122    6.82
seq1    129     130     5mC     640     +       129     130     0,0,0   8129    3.24
seq1    134     135     5mC     498     +       134     135     0,0,0   8134    2.69
seq1    195     196     5mC     646     +       195     196     0,0,0   8195    1.53
seq1    229     230     5mC     730     +       229     230     0,0,0   8227    4.46
seq1    267     268     5mC     532     +       267     268     0,0,0   8265    6.27
seq1    282     283     5mC     537     +       282     283     0,0,0   8280    11.51
seq1    311     312     5mC     614     +       311     312     0,0,0   8309    2.37
seq1    322     323     5mC     633     +       322     323     0,0,0   8320    3.80
seq1    334     335     5mC     292     +       334     335     0,0,0   8332    9.92
seq1    350     351     5mC     789     +       350     351     0,0,0   8348    5.34
seq1    415     416     5mC     736     +       415     416     0,0,0   8411    6.02
seq1    419     420     5mC     733     +       419     420     0,0,0   8414    4.18
seq1    428     429     5mC     654     +       428     429     0,0,0   8423    3.72
seq1    430     431     5mC     697     +       430     431     0,0,0   8425    2.57
seq1    436     437     5mC     625     +       436     437     0,0,0   8430    4.38
seq1    439     440     5mC     667     +       439     440     0,0,0   8433    3.11
seq1    483     484     5mC     548     +       483     484     0,0,0   8473    6.88
seq1    488     489     5mC     744     +       488     489     0,0,0   8476    1.81
seq1    499     500     5mC     669     +       499     500     0,0,0   8485    10.54
seq1    502     503     5mC     695     +       502     503     0,0,0   8488    10.12
seq1    514     515     5mC     634     +       514     515     0,0,0   8496    4.69
seq1    517     518     5mC     704     +       517     518     0,0,0   8499    7.65
seq1    552     553     5mC     683     +       552     553     0,0,0   8525    4.65
seq1    572     573     5mC     722     +       572     573     0,0,0   8536    6.05
seq1    575     576     5mC     739     +       575     576     0,0,0   8539    3.69
seq1    590     591     5mC     657     +       590     591     0,0,0   8550    4.87
seq1    594     595     5mC     672     +       594     595     0,0,0   8554    2.50
seq1    605     606     5mC     642     +       605     606     0,0,0   8562    3.93
seq1    641     642     5mC     665     +       641     642     0,0,0   8587    3.27
seq1    647     648     5mC     776     +       647     648     0,0,0   8591    5.54
seq1    652     653     5mC     698     +       652     653     0,0,0   8594    2.95
seq1    664     665     5mC     720     +       664     665     0,0,0   8605    6.85
seq1    667     668     5mC     771     +       667     668     0,0,0   8608    7.05
seq1    675     676     5mC     692     +       675     676     0,0,0   8613    4.84
seq1    702     703     5mC     669     +       702     703     0,0,0   8630    5.50
seq1    731     732     5mC     567     +       731     732     0,0,0   8652    4.62
seq1    738     739     5mC     606     +       738     739     0,0,0   8654    4.44
seq1    760     761     5mC     746     +       760     761     0,0,0   8662    4.73
seq1    771     772     5mC     727     +       771     772     0,0,0   8667    5.20
seq1    778     779     5mC     787     +       778     779     0,0,0   8668    3.81
seq1    824     825     5mC     792     +       824     825     0,0,0   8656    4.24
seq1    825     826     5mC     750     -       825     826     0,0,0   4       0.00
seq1    841     842     5mC     823     +       841     842     0,0,0   8636    3.20
seq1    842     843     5mC     142     -       842     843     0,0,0   7       0.00
seq1    853     854     5mC     772     +       853     854     0,0,0   8601    3.15
seq1    854     855     5mC     714     -       854     855     0,0,0   7       0.00
seq1    855     856     5mC     753     +       855     856     0,0,0   8588    2.39
seq1    856     857     5mC     285     -       856     857     0,0,0   7       0.00
</details>

<details>
<summary>Methylated data</summary>

seq1    38      39      5mC     409     +       38      39      0,0,0   8037    52.01
seq1    39      40      5mC     1000    -       39      40      0,0,0   1       100.00
seq1    49      50      5mC     647     +       49      50      0,0,0   8048    66.53
seq1    50      51      5mC     0       -       50      51      0,0,0   1       0.00
seq1    54      55      5mC     829     +       54      55      0,0,0   8053    80.78
seq1    55      56      5mC     0       -       55      56      0,0,0   1       0.00
seq1    57      58      5mC     743     +       57      58      0,0,0   8056    83.30
seq1    58      59      5mC     0       -       58      59      0,0,0   1       0.00
seq1    75      76      5mC     776     +       75      76      0,0,0   8074    90.37
seq1    76      77      5mC     1000    -       76      77      0,0,0   1       100.00
seq1    106     107     5mC     517     +       106     107     0,0,0   8100    75.29
seq1    107     108     5mC     750     -       107     108     0,0,0   4       100.00
seq1    116     117     5mC     173     +       116     117     0,0,0   8106    63.14
seq1    117     118     5mC     1000    -       117     118     0,0,0   5       80.00
seq1    122     123     5mC     602     +       122     123     0,0,0   8111    40.39
seq1    123     124     5mC     400     -       123     124     0,0,0   5       100.00
seq1    129     130     5mC     301     +       129     130     0,0,0   8118    29.42
seq1    130     131     5mC     1000    -       130     131     0,0,0   5       40.00
seq1    134     135     5mC     218     +       134     135     0,0,0   8123    46.62
seq1    135     136     5mC     400     -       135     136     0,0,0   5       0.00
seq1    195     196     5mC     323     +       195     196     0,0,0   8178    16.52
seq1    196     197     5mC     800     -       196     197     0,0,0   5       75.00
seq1    229     230     5mC     883     +       229     230     0,0,0   8210    93.37
seq1    230     231     5mC     600     -       230     231     0,0,0   5       33.33
seq1    267     268     5mC     492     +       267     268     0,0,0   8238    80.97
seq1    268     269     5mC     600     -       268     269     0,0,0   5       66.67
seq1    282     283     5mC     274     +       282     283     0,0,0   8253    47.90
seq1    283     284     5mC     800     -       283     284     0,0,0   5       50.00
seq1    311     312     5mC     344     +       311     312     0,0,0   8279    68.89
seq1    312     313     5mC     1000    -       312     313     0,0,0   5       60.00
seq1    322     323     5mC     188     +       322     323     0,0,0   8290    39.78
seq1    323     324     5mC     800     -       323     324     0,0,0   5       50.00
seq1    334     335     5mC     395     +       334     335     0,0,0   8301    28.72
seq1    335     336     5mC     400     -       335     336     0,0,0   5       0.00
seq1    350     351     5mC     682     +       350     351     0,0,0   8316    24.33
seq1    351     352     5mC     400     -       351     352     0,0,0   5       100.00
seq1    415     416     5mC     822     +       415     416     0,0,0   8320    37.11
seq1    416     417     5mC     800     -       416     417     0,0,0   5       75.00
seq1    419     420     5mC     676     +       419     420     0,0,0   8320    5.76
seq1    420     421     5mC     800     -       420     421     0,0,0   5       50.00
seq1    428     429     5mC     610     +       428     429     0,0,0   8324    35.23
seq1    429     430     5mC     800     -       429     430     0,0,0   5       75.00
seq1    430     431     5mC     533     +       430     431     0,0,0   8320    28.19
seq1    431     432     5mC     1000    -       431     432     0,0,0   5       60.00
seq1    436     437     5mC     545     +       436     437     0,0,0   8325    51.28
seq1    437     438     5mC     800     -       437     438     0,0,0   5       75.00
seq1    439     440     5mC     415     +       439     440     0,0,0   8328    27.31
seq1    440     441     5mC     800     -       440     441     0,0,0   5       75.00
seq1    483     484     5mC     842     +       483     484     0,0,0   8353    92.85
seq1    484     485     5mC     750     -       484     485     0,0,0   4       0.00
seq1    488     489     5mC     854     +       488     489     0,0,0   8352    92.39
seq1    489     490     5mC     500     -       489     490     0,0,0   4       50.00
seq1    499     500     5mC     791     +       499     500     0,0,0   8333    90.69
seq1    500     501     5mC     750     -       500     501     0,0,0   4       0.00
seq1    502     503     5mC     862     +       502     503     0,0,0   8327    89.69
seq1    503     504     5mC     250     -       503     504     0,0,0   4       0.00
seq1    514     515     5mC     131     +       514     515     0,0,0   8239    43.79
seq1    515     516     5mC     1000    -       515     516     0,0,0   4       25.00
seq1    517     518     5mC     613     +       517     518     0,0,0   8242    83.87
seq1    518     519     5mC     750     -       518     519     0,0,0   4       66.67
seq1    552     553     5mC     734     +       552     553     0,0,0   7974    38.37
seq1    553     554     5mC     440     -       553     554     0,0,0   25      0.00
seq1    572     573     5mC     589     +       572     573     0,0,0   7967    28.09
seq1    573     574     5mC     674     -       573     574     0,0,0   43      20.69
seq1    575     576     5mC     554     +       575     576     0,0,0   7967    64.98
seq1    576     577     5mC     255     -       576     577     0,0,0   43      18.18
seq1    590     591     5mC     680     +       590     591     0,0,0   7978    68.49
seq1    591     592     5mC     714     -       591     592     0,0,0   42      13.33
seq1    594     595     5mC     673     +       594     595     0,0,0   7980    90.74
seq1    595     596     5mC     738     -       595     596     0,0,0   42      9.68
seq1    605     606     5mC     376     +       605     606     0,0,0   7976    72.17
seq1    606     607     5mC     619     -       606     607     0,0,0   42      15.38
seq1    641     642     5mC     630     +       641     642     0,0,0   7988    62.49
seq1    642     643     5mC     625     -       642     643     0,0,0   40      12.00
seq1    647     648     5mC     742     +       647     648     0,0,0   7986    77.92
seq1    648     649     5mC     600     -       648     649     0,0,0   40      8.33
seq1    652     653     5mC     321     +       652     653     0,0,0   7988    50.78
seq1    653     654     5mC     538     -       653     654     0,0,0   39      19.05
seq1    664     665     5mC     690     +       664     665     0,0,0   7997    74.94
seq1    665     666     5mC     692     -       665     666     0,0,0   39      11.11
seq1    667     668     5mC     587     +       667     668     0,0,0   8000    43.96
seq1    668     669     5mC     552     -       668     669     0,0,0   38      14.29
seq1    675     676     5mC     573     +       675     676     0,0,0   7988    50.01
seq1    676     677     5mC     578     -       676     677     0,0,0   38      27.27
seq1    702     703     5mC     654     +       702     703     0,0,0   7998    76.86
seq1    703     704     5mC     322     -       703     704     0,0,0   31      10.00
seq1    731     732     5mC     460     +       731     732     0,0,0   8013    36.13
seq1    732     733     5mC     640     -       732     733     0,0,0   25      18.75
seq1    738     739     5mC     627     +       738     739     0,0,0   8019    72.84
seq1    739     740     5mC     173     -       739     740     0,0,0   23      0.00
seq1    760     761     5mC     844     +       760     761     0,0,0   8029    78.86
seq1    761     762     5mC     523     -       761     762     0,0,0   21      9.09
seq1    771     772     5mC     523     +       771     772     0,0,0   8030    55.04
seq1    772     773     5mC     578     -       772     773     0,0,0   19      9.09
seq1    778     779     5mC     721     +       778     779     0,0,0   8034    64.81
seq1    779     780     5mC     421     -       779     780     0,0,0   19      75.00
seq1    824     825     5mC     789     +       824     825     0,0,0   7836    83.07
seq1    825     826     5mC     619     -       825     826     0,0,0   21      15.38
seq1    841     842     5mC     748     +       841     842     0,0,0   7412    81.14
seq1    842     843     5mC     200     -       842     843     0,0,0   20      50.00
seq1    853     854     5mC     844     +       853     854     0,0,0   7014    80.59
seq1    854     855     5mC     521     -       854     855     0,0,0   23      25.00
seq1    855     856     5mC     763     +       855     856     0,0,0   6943    84.82
seq1    856     857     5mC     333     -       856     857     0,0,0   33      36.36

</details>

Do you have any idea what might have gone wrong ? 

Thanks in advance for your help.

**Comment by cjw85** [comment]
Hi @e-sollier,

I suspect whatever the reason for reporting only around coverage of 9000 is the same cause of the lack of `-` strand entries (I'm assuming the sample preparation hasn't somehow biased that).

I cannot explain these observations. I vaguely recall something in the HTSlib pileup API (which modbam2bed uses) that may limit the number of alignments returned. I'd need to check that. I cannot think of anything in the modbam2bed code itself that would limit the results to ~9000.

**Comment by cjw85** [comment]
I asked a colleague who suspects the same cause as myself. We believe its related to how `samtools mpileup` has a `--max-depth` option.

To get you going, I would suggest filtering your BAM to two BAMs, one each for `+` and `-` alignments. This can be done with:
```
samtools view -c -F 16 <bamfile>
samtools view -c -f 16 <bamfile>
``` 
You can then give both of these files to modbam2bed simultaneously to produce a single BED. I *think* this will work because the depth limit coming from htslib is per input file.

**Comment by e-sollier** [comment]
Thanks a lot for the very quick reply!

I did as you suggested, splitting the bam files into + or - alignments, and used these 2 files as input to modbam2bed. This indeed allowed me to get results for both the + and - strands. The coverage on each strand is limited to around 8000, but this is sufficient for my purposes (getting the percentage of modified bases).

Although I don't really need it, it might still be useful to add the option in modbam2bed to use more than 8000 reads at a position. I had a quick look at htslib and there is indeed a `maxcnt` parameter whose default value is 8000 (https://github.com/samtools/htslib/blob/develop/sam.c#L5395), but there is also a function to set the value of this parameter (https://github.com/samtools/htslib/blob/develop/sam.c#L5918).

**Comment by cjw85** [comment]
@e-sollier 

I've added a `--max_depth` option analogous to the `samtools mpileup` option. There's a difference however, I elected to not limit the depth by default.
