### ISSUE TITLE
the coverage we really want is N_mod+N_canon

### ISSUE THREAD

**Issue by benbfly** [epi2me-labs/modbam2bed#11]
For most downstream analysis, the coverage we care about is the number of *informative* reads, in other words N_mod+N_canon.  But the only coverage field you provide is column 10, which is all reads (including non-informative ones).

We can calculate N_mod+N_canon from the values in column 5 and column 10, but it is non-obvious.  I think it would be much better to have column 10 be N_mod+N_canon, and give instructions how to calculate N_Mod+N_canon+N_filt+N_sub+N_del from column 5 and column 10.

**Comment by andrewgalbraith21** [comment]
To follow up, has there been any consideration to modify column 10 according to the above comment? I think for most utilizations, this would be best and is a fairly straightforward change.

**Comment by cjw85** [comment]
It was previously outlined quite precisely why the definition is unlikely to be changed: https://github.com/nanoporetech/megalodon/issues/247#issuecomment-1040287905

The choice is yet more relevant in the context of the most recent line of basecallers that output a multinomial call across {C, 5mC, 5hmC}.

**Comment by benbfly** [comment]
I stick by my original assertion that most users will want to use the field 10 together side by side field 11 to quantify number of confidently modified vs. confidently unmodified reads.  It generally doesn't make sense to talk about modification level on a read that has a substituted or deleted base.  I'm not sure how multinomial (C,5mC,5hmC) changes this, since I expect those would either be counted as canonical (if it is confidently called as a *different* modification) or filt (if it can not distinguish between canonical and the 2 or more modifications).

In any case, it's probably too late to change this because there are a lot of files out there now generated by the existing version, and these might be mis-interpreted in the future which would cause confusion and misinterpretation.

If I were designing this from scratch, I would just leave out column 10 altogether and output all five different N counts by default (i.e. make the --extended version the default). Then there would be no room for confusion.

**Comment by cjw85** [comment]
modbam2bed is now deprecated. This won't be fixed.
