### ISSUE TITLE
Passing multiple sorted bamfiles VS one sorted and merged bamfile to modbam2bed

### ISSUE THREAD

**Issue by TeiturAK** [epi2me-labs/modbam2bed#13]
Hi,

I've been running Guppy to do the modified basecalls before running modbam2bed. 

Guppy produces multiple bam files which I then sort, index and merge before passing the combined output to modbam2bed which then outputs the results without any errors. 

However, when I try passing multiple unmerged bam files that are sorted and indexed (the same ones as I did a merge of) I get the following error with no output:

```
Fetched PA_chr01, 1681021526 1681021526
Processing: PA_chr01:0-1681021526
Failed to find reference sequence 'PA_chr01' in bam.
Failed to find reference sequence 'PA_chr01' in bam.
Failed to find reference sequence 'PA_chr01' in bam.
Failed to find reference sequence 'PA_chr01' in bam.
```

and on it goes for all the reference points in the genome. 

This is curious. Is it because of a misinterpretation of the modbam2bed manual? 

I would be very grateful if you could shine some light on why the merged bam file works but several unmerged does not as Im about to scale up my analysis. To me it looks like passing several bam files along the intended use?

Best
Teitur

**Comment by cjw85** [comment]
It is intended that you should be able to iterate over multiple independent BAMs. Could you provide a sample set of your BAM files which reproduces this error. It seems to me that the indexes of at least some of your BAMs do not contain all the sequences from your reference file.

The code does function correctly for the set I have: outputs from Guppy for GIAB HG002 aligned to GRCh38.

**Comment by TeiturAK** [comment]
Thank you, massively appreciate this. I have invited you to a repository with a link to the data.

**Comment by TeiturAK** [comment]
I've added some additional info in the repository and how you can get in contact with me if needed!

Thanks again!

**Comment by cjw85** [comment]
Thank you @TeiturAK, I'll take a look.

**Comment by TeiturAK** [comment]
> It is intended that you should be able to iterate over multiple independent BAMs. Could you provide a sample set of your BAM files which reproduces this error. It seems to me that the indexes of at least some of your BAMs do not contain all the sequences from your reference file.
> 
> The code does function correctly for the set I have: outputs from Guppy for GIAB HG002 aligned to GRCh38.

Thank you, yes that was the case. I was only using a small set of fast5s to produce these bams which made them lack this information.
