### ISSUE TITLE
Failed to find reference sequence 'contig_1' in bam.

### ISSUE THREAD

**Issue by Kirk3gaard** [epi2me-labs/modbam2bed#15]
Hi

I did call modifications with guppy (dna_r9.4.1_450bps_modbases_5mc_hac_prom.cfg and --bam_out)
and then I stumbled upon this tool. 

However, when I run it with the following command
modbam2bed  --mod_base=5mC genome.fa guppy_methylation/pass/*.bam

I get the following error;
Failed to find reference sequence 'contig_1' in bam.

Should I rerun guppy with the "--align_ref" option or what would be the trick to use the modbam from guppy and align the reads to the reference?

Best regards
Rasmus

**Comment by cjw85** [comment]
The program expects aligned BAM files as input so you either need to rerun Guppy giving it a reference (such that it internally uses minimap2 to perform alignment on the reads) or pipe the output of samtools fastq through minimap2 using the options to write SAM tags to fastq headers and write them back to minimap2s SAM output. I forget the command line switches, in the case of minimap2 it's not documented in the command line help only the man pages.

**Comment by marcus1487** [comment]
For the `samtools fastq`/`minimap2` workaround: https://github.com/lh3/minimap2/issues/870#issuecomment-1033306393

**Comment by Kirk3gaard** [comment]
Okay I feared that would be the case. 

Any chance that modbam2bed could handle the mapping in the future since it still gets the reference as input anyway? This way there would be no need to rebasecall every subset of fast5s from a run with a matching reference.

Thanks for the hint for the workaround. So something like this should work?

samtools fastq -TXX,YY read.mod.bam | minimap2 -ax map-ont -y ref.fa - | samtools view -Sb - |  samtools sort - > aln.mod.bam

Or would the other samtools operations also need to have a setting that keeps the tags?

Best regards
Rasmus

**Comment by cjw85** [comment]
> Any chance that modbam2bed could handle the mapping in the future since it still gets the reference as input anyway?

I think that is outside the scope of the program. 

Your command looks correct from what I recall.

**Comment by Kirk3gaard** [comment]
Okay. Thanks.

**Comment by marcus1487** [comment]
Minor comment that you'll need to convert the `-TXX,YY` to `-TMM,ML` or `-TMm,Ml` depending on the tag format (lower case was used in preliminary spec before full inclusion in the samtools tag spec).
