### ISSUE TITLE
"-1" positions in output using modbampy

### ISSUE THREAD

**Issue by pterzian** [epi2me-labs/modbam2bed#16]
Hello,

First of all thank you for providing this tools.

Similarly to #2, I am trying to use you `modbampy` package to produce a per-read calls tabular file from a modBam because it seems to be the only tool to do that. I pretty much did what you suggested yet I might have made a mistake somewhere:

```
from argparse import ArgumentParser

parser = ArgumentParser(description='write per-reads calls to tsv file from modbam file')
parser.add_argument('-i','--modbam',type=str,required=True,help='Path to bam file')
parser.add_argument('-o','--output',type=str,required=True,help='Name of output file')
parser.add_argument('-c','--chromsize',type=str,required=True,help='Name of output file')
parser.add_argument('-v','--version',action='version',help='print version',version='%(prog)s v0.1')
args = parser.parse_args()

with ModBam(args.modbam) as bam, open(args.output, 'w') as f, open(args.chromsize) as chrm:
                for l in chrm :
                        lp = l.rstrip()
                        larray = lp.split("\t")
                        for read in bam.reads(larray[0], 1, int(larray[1])):
                                for pos_mod in read.mod_sites:
                                        line = '\t'.join(map(str,[*pos_mod, larray[0]]))
                                        f.write(line)
                                        f.write("\n")
```

I can find the positions I am looking for in the output file but I also have some weird genomic positions :

```
sample/17892231/ccs       -1      133     +       0       C       m       203     1
sample/17892231/ccs       -1      201     +       0       C       m       203     1
sample/17892231/ccs       -1      395     +       0       C       m       15      1
sample/17892231/ccs       -1      441     +       0       C       m       129     1
sample/17892231/ccs       -1      562     +       0       C       m       104     1
``` 

Any idea where it could come from ?

Something tells me it comes from my code as modbam2bed worked like a charmed to produce a bedmethyl from the same bam.

Cheers,
Paul

**Comment by cjw85** [comment]
Hi @pterzian,

Your code iterates the BAM by read, and then positions in the read. Some positions in the reads will not have a reference position associated with them; either the base is softclipped in the alignment or possibly is an insert (I'm not sure on this second case, insertions may report the preceding reference position).

**Comment by pterzian** [comment]
I didn't think about that. Ty again
