### ISSUE TITLE
Adding motif context to modbampy

### ISSUE THREAD

**Issue by rrazaghi** [epi2me-labs/modbam2bed#17]
Hi @cjw85,

I was wondering if it would be easy to include motif context in the modbampy read parser. maybe something like outputting -/+ 3-4 bases so frequently used motifs like CpG, GpC, GATC can be identified easily? 

Thanks a lot!

**Comment by cjw85** [comment]
The way this is done in the C program is simply to look up the reference sequence at the time before entries are output, it's not doing anything special to optimise this.

When using the Python API the reference position is returned so it should not be difficult to grab the corresponding motif if used in concert with a Fasta parser.

**Comment by rrazaghi** [comment]
Thanks, Chris! pysam.FastaFile solved it as you said!
