### ISSUE TITLE
Does modbam2bed handle soft clips?

### ISSUE THREAD

**Issue by billytcl** [epi2me-labs/modbam2bed#18]
Just a quick q -- does modbam2bed handle soft clips properly? 

We have a bunch of native barcoded samples and running Guppy v6.1.2's integrated methylation caller/aligner on them, which produces bam files with soft clip. 

Megalodon's mod_mappings.bam output removes the soft clips, and that's what I've been using for generating the modbam.bed. Just wondering if the specific barcoded use case is supported, or whether I should continue using megalodon.

**Comment by cjw85** [comment]
Soft-clipped bases aren't considered as part of the aligned portion of a read. As such modbam2bed does not assign them to any reference position.

Going further into your question, I think you are really asking/worried that bases from sequencing adapters and barcodes might be included in the alignment (through improper clipping of these portions of the read). Megalodon has no special handling of these sequences; and modbam2bed is simply agnostic as all it does it process the alignments in the given BAM file.

Our recommende approach would be to use Guppy with its integrated remora algorithm and enable the demultiplexing and trimming options (which have knowledge of the adapters and barcode sequences). This should give you as clean alignments as possible.

**Comment by billytcl** [comment]
Thanks!! Actually, does the guppy barcode trimming work well now (--trim_adapters I believe?)? Way back (years ago) when I tried it out and it chopped the first part of the barcode adapter, but not the sequence that's right next to the insert. Not sure if I was doing something weird here.

**Comment by cjw85** [comment]
Trimming in Guppy should be better than relying on the aligner to truncate alignments with soft-clipping because the trimming has knowledge about what sequences to trim. The aligner will extend alignment into the non-insert region until the alignment score is adversely affected; this could include the non-insert bases if they happen to match the reference bases.
