### ISSUE TITLE
-b, --mod_threshold

### ISSUE THREAD

**Issue by carolinehey** [epi2me-labs/modbam2bed#19]
What is the default --mod_threshold?
If i want to set this threshold do i then use the probability score in the Ml tag values and chose a threshold between 0-255 or do i set it in relation to the transformed percentage probability (0-100 %) ?

**Comment by cjw85** [comment]
The defaults are such that bases with a modification probability in the range [0.33, 0.66] are filtered. The command-line arguments should be set as probabilities int he range [0, 1].
