### ISSUE TITLE
Any way to get this to output per read mods in a bam file like megalodon?

### ISSUE THREAD

**Issue by billytcl** [epi2me-labs/modbam2bed#2]
I'm trying to use Bonito's new remora-based methylation calling combined with this program to create aggregate bedmethyl files. One additional output from megalodon is the per_read_mods text file, which gives you the per-read positional methylation probabilities. Is there a way to hack this program to do it, or an easy way to do it from shell script by parsing out the tags?

**Comment by cjw85** [comment]
The `modbam2bed` program does not provide a table of per-read information, as this is not seen as useful in and of itself.

The Python library documented in the [README](https://github.com/epi2me-labs/modbam2bed#python-package) can provide the information you need.

Can you describe the task you are trying to achieve, i.e. what you intend to do having acquired the table of counts? Perhaps that is a task that can be added as a discrete tool (to either the Python library of a discrete program).

**Comment by billytcl** [comment]
Thanks for the clarification! The Python library looks useful - looks like
I didn't scroll down far enough in the readme.

We are developing a per-read classifier based on methylation profiles, so
the per-read information is really useful for us (and that's why megalodon
has been indispensable). The python package looks to do exactly what I
need, but I think I still need to filter positions on the CG sites, right?
Is there a simple function in the library that allows me to do it quickly?

A discrete tool would be cool, but I think if there is a way to do it
within the confines of the existing package then that would be better since
it would be less work for everyone. :)

Billy

**Comment by cjw85** [comment]
The CG filtering in `modbam2bed` is implemented only during output. There's nothing similar in the Python library (its outputting every bit of modification information stored within the BAM record) so you would have to cross-reference the co-ordinates output for the records with the reference sequence and perform any other filtering you needed or wanted.

**Comment by billytcl** [comment]
Would it work if I used megalodon to output all the CG motifs as a bed and
then do a bedtools intersect? Or is that too slow (eg the read output file
is massive)? I’m not sure how the site filtering is implemented in the
modbam2bed tool.

Billy

**Comment by cjw85** [comment]
I'm intending that within your "per-read classifier based on methylation profiles" program you perform the cross-referencing of the records from each read with the reference sequence. I think you want to avoid ever writing the per-read per-site data to a text file, only to read it all back in to another program.

Something like:

```
from pysam import FastaFile
with FastaFile(...):
    # read reference sequence

from modbampy import ModBam
with ModBam(args.bam, args.chrom, args.start, args.end) as bam:
    for read in bam.reads():
        for pos_mod in read.mod_sites():
            qname, rpos, qpos, strand, mod_strand, cbase, mbase, score = pos_mod
            if strand == "+" and reference[rpos] == 'C' and reference[rpos + 1] == 'G':
                # this is a CG site, accumulate information
            else if # similar for strand == '-'
        # now have everything to do with this read (alignment to be precise)
        # so can process read based on mod information
```

**Comment by billytcl** [comment]
That's way more elegant! Thanks for pointing me to the python library.

**Comment by billytcl** [comment]
Just to open this up again -- is there a way to have it iterate over a bam file like pysam without needing to specify the chr, start, and end position? Secondly, if there is a way to do it, how to I query for the aligned chromosome contig name? I see that in pysam/htslib they're working slowly on an interface to parse the Mm and Ml tags like how this library does it, but nothing has happened recently.

Eg. what I'd like is something like:

```
with ModBam(args.bam) as bam:
      for read in bam.reads(): #normally in pysam this would be fetch()
          for pos_mod in read.mod_sites():
              qname, rname, rpos, qpos, strand, mod_strand, cbase, mbase, score = pos_mod #rname would be the aligned reference contig name

```

**Comment by cjw85** [comment]
I would be possible to implement this, but I can't give a timeline. In the meantime you could simply use pysam to get the reference names and lengths and pass then one by one to the ModBam class.

I don't follow your second question, or at least how it is distinct from your first.

There is currently no work that I am aware of to bring the functionality to pysam (I've opened a issues here: https://github.com/pysam-developers/pysam/issues/1052). This library uses the functionality that has been implemented into htslib.

**Comment by billytcl** [comment]
Thanks! I'll have to try that out. 

The second question is not really distinct from the first -- I just noticed that it wasn't obvious how to get the aligned reference name from the read function inside ModBam (ie. as if you were doing a pysam fetch), but it's moot because you had to specify it in the first place when creating the ModBam object.

**Comment by cjw85** [comment]
The interface in v0.5.0 has been changed to separate opening the file from region queries.
