### ISSUE TITLE
More choices for modified base calls (feature request)

### ISSUE THREAD

**Issue by sathish-t** [epi2me-labs/modbam2bed#20]
Hello, 

I'm using modbampy. Is it possible to include numeric CheBI tags as possible values to the mod_base option of the command below? Thanks!

>  bam.pileup(args.chrom, args.start, args.end, low_threshold=0.33, high_threshold=0.66, mod_base="m")

Regards
Sathish

**Comment by cjw85** [comment]
It should be possible to extend modbampy to do this.

The htslib API stores the modified base as an integer. If its negative, its intepreted as a CheBI code:
https://github.com/samtools/htslib/blob/d67da0ecee170b717b8933e2a50f6d10f2c30c1e/test/pileup_mod.c#L113
and if positive a character representation (as modbampy does currently)

**Comment by sathish-t** [comment]
I'm dealing with data with base modifications that are not a part of the standard table in pg 9 of https://samtools.github.io/hts-specs/SAMtags.pdf. My choices are to use the 'any modification' single letter codes or the CheBI codes themselves. I am using modbampy with the ambiguous single-letter codes at the moment but would like to use the CheBI codes directly.

**Comment by sathish-t** [comment]
[dummyFiles.zip](https://github.com/epi2me-labs/modbam2bed/files/9021656/dummyFiles.zip)

Hi cjw85,

Thanks for v0.6.0. I'm running into some errors when I use numeric CheBI tags in modbampy.

In the reference zip file, I have created some dummy bam and reference fasta files. The bam files come in two flavors: suffix Chebi denotes I've used MM:Z:T+472252?,... and suffix T denotes I've used MM:Z:T+T?,... to denote modifications. So I've used a specific chebi code in one and the generic T tag in the other.

Then, I ran the code excerpt below from the documentation. As you can see the 'T' version runs fine, but the 472252 version throws up errors.

I would also like to use CheBI numbers in the modbam2bed program. Even if numbers are too hard, a generic tag like 'T' will help me greatly! All the single letter codes in the table on pg 9 of https://samtools.github.io/hts-specs/SAMtags.pdf for thymidine modifications seem to work except the generic tag of 'T'. 

Thanks!

    from modbampy import ModBam
    
    with ModBam("dummyT.bam") as bam:
        for read in bam.reads("dummyII",3,36):
            for pos_mod in read.mod_sites:
                print(*pos_mod)

>fffffff1-10d2-49cb-8ca3-e8d48979001b 15 12 - 0 T T 3
>fffffff1-10d2-49cb-8ca3-e8d48979001b 16 13 - 0 T T 3
>fffffff1-10d2-49cb-8ca3-e8d48979001b 19 16 - 0 T T 4
>fffffff1-10d2-49cb-8ca3-e8d48979001b 22 19 - 0 T T 3
>fffffff1-10d2-49cb-8ca3-e8d48979001b 23 20 - 0 T T 182

    with ModBam("dummyChebi.bam") as bam:
        for read in bam.reads("dummyII",3,36):
            for pos_mod in read.mod_sites:
                print(*pos_mod)

>Traceback (most recent call last):
>  File "<stdin>", line 3, in <module>
>  File "/usr/local/lib/python3.10/site-packages/modbampy/__init__.py", line 296, in mod_sites
>    chr(m.canonical_base), chr(m.modified_base), m.qual)
>ValueError: chr() arg not in range(0x110000)

**Comment by cjw85** [comment]
Apologies, I must admit that I didn't get a chance to test the code completely; only the minor changes needed to support numeric codes. I will add your data as tests. The Python code is failing because its wanting to interpret the numeric value of the ChEBI code as data corresponding to an ASCII character value --- it doesn't know that if thats not possible, it should leave the value as is.

I did not implement generic ChEBI codes into modbam2bed because as it stands the code contains a list of the modified bases, their names, and analogous unmodified forms (basically the table on page 9 of the spec [common.h#L15](https://github.com/epi2me-labs/modbam2bed/blob/master/src/common.h#L15)). The code needs to know the unmodified form because it uses that to know the complement base on the second strand for reverse-mapped reads.

I can add in the "Ambiguity code; any X mod" entries from the table; I don't know why I skipped these.

I'll fix the Python API and add the generic mods ASAP.

**Comment by sathish-t** [comment]
Hi cjw85, Thanks for your reply. I am writing a package to convert modification data to bam from a different format and it's still in the testing stages. I would say my dummy bam files are not of a good quality yet. So it's ok if you use them for tests w.r.t. this issue but I don't think they are good for general tests.

**Comment by sathish-t** [comment]
Hi cjw85, 

I seem to have found another bug. But I am new to these file formats and I might be making a mistake. I am still using the files I included in my zip file, which is why I am posting in this thread.

The reference fasta is

    cat dummy.fa
<pre>
>dummyI
AGCTAGCTATCGTTTCTGTGAG
>dummyII
GGGGGGGGGGTCTCTAACGACCAA
>dummyIII
CCACACCACACCCACACACCCACACATCAAATCCACACCACACCACACCC
TGGGAGCCACCATAACGGCCTTATTG
</pre>

The bam file without headers is

    samtools view dummy.bam

<pre>
5d10eb9a-aae1-4db8-8ec6-7ebb34d32575    0       dummyI  10      255     8M      *       0       8       TCGTTTCT        *       MM:Z:T+T?,0,0,0,0,0;    ML:B:C,4,7,9,8,6   X
R:i:97586873    XA:Z:5d10eb9a-aae1-4db8-8ec6-7ebb34d32575_dummyI_9_17_fwd
a4f36092-b4d5-47a9-813e-c22c3b477a0c    0       dummyIII        24      255     48M     *       0       48      ACATCAAATCCACACCACACCACACCCTGGGAGCCACCATAACGGCCT        *  M
M:Z:T+T?,0,0,0,0,0;     ML:B:C,221,242,3,47,239 XR:i:172963337  XA:Z:a4f36092-b4d5-47a9-813e-c22c3b477a0c_dummyIII_23_71_fwd
fffffff1-10d2-49cb-8ca3-e8d48979001b    16      dummyII 4       255     21M     *       0       21      GGGGGGGTCTCTAACGACCAA   *       MM:Z:T+T?,5,0,0,0,0;    ML:B:C,182,3
,4,3,3  XR:i:268435455  XA:Z:fffffff1-10d2-49cb-8ca3-e8d48979001b_dummyII_3_36_rev
</pre>

If you look at the third line of the bam file, you will see that the reverse-complemented entry fffffff1-10d2-49cb-8ca3-e8d48979001b  has the sequence GGGGGGGTCTCTAACGACCAA and the modification data MM:Z:T+T?,5,0,0,0,0;    ML:B:C,182,3,4,3,3.

The modification string is clearly wrong as once you've skipped 5 thymidines on the reverse complemented strand, there are no thymidines left! Yet, modbampy runs fine as evidenced by my snippets from https://github.com/epi2me-labs/modbam2bed/issues/20#issuecomment-1171434215

Do you think this is a bug or am I making a mistake? Thanks!

**Comment by cjw85** [comment]
I have fixed the issues noted above in v0.6.2.

modbam2bed relies on functionality from htslib for parsing of SAM records, including the MM and ML tags. I'll need to pass on your observations with malformed tags to the htslib developers.

(After a brief review of the code, I see that the Python module is not checking the return value of the function [`bam_parse_basemod`](https://github.com/samtools/htslib/blob/7fef9d3acaf4ea51dcd6a9fd74742e17c90ec44a/sam.c#L6164). However adding in a check shows that this function is always returning successfully)
