### ISSUE TITLE
Supplying -m argument multiple times only seems to output the data from last option provided

### ISSUE THREAD

**Issue by mp15** [epi2me-labs/modbam2bed#25]
Version: a51fc3549a413eb1bff14085944f7e0b31a507b9
I tried:
```
modbam2bed/modbam2bed -e -m 5mC -m 5hmC --cpg --chg -t 10 -p clive /lustre/scratch117/core/sciops_repository/references/Homo_sapiens/GRCh38_full_analysis_set_plus_decoy_hla/all/fasta/Homo_sapiens.GRCh38_full_analysis_set_plus_decoy_hla.fa PAM63114/bonito_calls.bam PAM63167/bonito_calls.bam PAM63974/bonito_calls.bam
```
This successfully completed but only output the 5hmC data not the 5mC data. One would expect either both output (in an interleaved fashion retaining sort order) or an error message saying that this combination is unsupported.

**Comment by cjw85** [comment]
This is an oversight, the program should error and warn that only one modified base can be processed at a time.

**Comment by cjw85** [comment]
modbam2bed is now deprecated. This won't be fixed.
