### ISSUE TITLE
No output 

### ISSUE THREAD

**Issue by charliechen912ilovbash** [epi2me-labs/modbam2bed#26]
Thanks for developing this useful tool.
I'm using this tool to convert the output BAM of Guppy v6.3.2, to obtain modified 5mC and 5hmC position. 
But I'm not sure why there's not any output from `modbam2bed`.
My commands are:
`modbam2bed -e -m 5hmC --cpg -t 10 $reference  $bam`
`modbam2bed -e -m 5mC --cpg -t 10 $reference  $bam`

The following is one of the reads in the input bam.
Is there anything looks weird ?
```
63bbf824-5873-44b4-a29d-3a48f334b4dc    0       chr21   5054147 0       *       *       0       246     CTCATCTGTGTACTTCGTTCAGTTACGTATTGCTCAGGACCTGCCTGCCGGGAGGGCTGCAGCTGAACTGCTGTTAGCGTGGGTGGCTCTGAATCAATGGCCCATTTTTCTGTGCAGTGTGTTGGGGGCAGCCTGAGCCTCTGCTCAGGTTGAACAGGAAGCAGGGAACCCTCTTGGAGCCTGAAGGGGTCCTGCTCCTGTGTCCTGACCAGCACTCATAGGGTCTGCTCTGTGGTCCTGACCTCC  %$'%$('%$$*&&'//.125---1'''-001202;/6>A88657451../.7<5530+./,,-124869;;:868.-,58))*+2338:/87=8@046**,54-,-?@=?78??DA?==<;01/-/30-3&&&222'''66/&%'*'''+56453-/.2),+'*,+-0.046/-,(&(&&(/56><54977,-2236'/*)*497541119346>=:))(),*(5/223:9843+*&'%'+,,/3-  cm:i:15 dv:f:0.0512     s1:i:109        s2:i:109        tp:A:P  MM:Z:C+h?,4,1,7,5;C+m?,4,1,7,5; ML:B:C,23,25,1,17,72,1,254,237  qs:i:10 mx:i:4  ch:i:1438       rn:i:4688       st:Z:2021-09-01T12:39:35Z       f5:Z:PAH62560_pass_ef4401c4_4428.fast5  ns:i:2761       ts:i:0  RG:Z:ef4401c4f5247554880fb681cb743588965f52fc_2021-05-17_dna_r9.4.1_minion_96_29d8704b
```

I tried the E.coli test data, and generated output successfully.

Also, the BAM file I generated with `guppy_basecaller  --bam_out --index -i $fast5 -s $out -c $cfg --align_ref $ref --device cuda:0:500G --minimap_opt_string " -t 1 -x map-ont --MD "  --num_callers 1` could not be visualized on IGV (only depth track shown, but the alignment track is empty), could I send a small BAM to you ?

**Comment by cjw85** [comment]
Hi @charliechen912ilovbash,

The record you have shown appears not to have a cigar string to illustrate the alignment. It doesn't however contain a 4 in column 2 to indicate the read is unaligned.

I would contact support@nanoporetech.com as the BAM that guppy has output appears not to make sense.

**Comment by charliechen912ilovbash** [comment]
Thanks for reply! Indeed, I checked other reads in the BAM, all of them do not have CIGAR.
