### ISSUE TITLE
CIGAR and query sequence lengths differ for

### ISSUE THREAD

**Issue by charliechen912ilovbash** [epi2me-labs/modbam2bed#28]
Hello,
I am using modbam2bed on a guppy v6.3.7 output bam.
my guppy command is:
`guppy_basecaller  --bam_out --index -i $fast5 -s $out -c /guppy/gpu/v6.3.7/ont-guppy/data/dna_r9.4.1_450bps_modbases_5hmc_5mc_cg_sup.cfg --align_ref hg38 --device cuda:0,1:400G   --num_callers 2`

my command is
`modbam2bed  -e -m 5mC --cpg  hg38 BAM`

and it shows
```
Analysing: 5-methylcytosine (5mC, C>m)
Fetched chr1, 248956422 248956422
Processing: chr1:0-248956422
[E::bam_read1] CIGAR and query sequence lengths differ for 4e1b8706-1a01-4c30-874c-7d731ed84052
```

my question is, when encountering this kind of read, will modbam2bed ignore it then jump to the next read (I supposed) ?
in the tested sample, in total 19,386,319 reads, there are ~4500 reads possess this error message.

**Comment by cjw85** [comment]
Yes the program will skip over these reads.

I'm intrigued that you have such reads, it suggests a bug in guppy.

**Comment by charliechen912ilovbash** [comment]
I see, thanks for replying.
By the way, do you know anyway to inspect these read in BAM? since `samtools view` does not work.

**Comment by cjw85** [comment]
Samtools will not work for the sam reason that modbam2bed will not work: they both use [htslib](https://www.htslib.org/) to read the data, and as far as htslib is concerned the data is currupt.

I think your offending BAM should be reported to support@nanoporetech.com.
