### ISSUE TITLE
add core alignment information to modbampy

### ISSUE THREAD

**Issue by rrazaghi** [epi2me-labs/modbam2bed#3]
Hi Chris,

I have been extensively using modbam2bed the past few months and it's been truly an amazing tool!

I currently have pythonic implementation using pysam (hopefully they will add this per your issue on their repo) to get mod states and some basic alignment stats. Clearly, my implementation is way slower so I wanted to use modbampy exclusively.
I was wondering if it would be feasible to add read.reference_start and read.reference_end to current implementation.
I can certainly parse a region twice with different HP values for Modbam instantialization but I was curious if you could add these as read.HP so its easier to parse a region just once instead?

Again thanks a lot for this tool! very helpful!

-Roham

**Comment by cjw85** [comment]
Hi @rrazaghi,

I didn't try too hard with the Python API as the desire was just to demonstrate the possibility and I didn't want to end up reinventing pysam!

If you make a list of methods and properties you want from either alignments or pileups I will look to add them when I next have a moment to work on this project.

**Comment by rrazaghi** [comment]
Makes total sense! Hopefully, pysam will catch up soon.

I really don't need anything beyond the reference_start and end positions currently as I am working on a visualization/clustering tool for modbams

Thanks!

**Comment by cjw85** [comment]
I've added various properties to the `ModRead` class a la pysam. The reference start and end co-ordinates are there. Some things I've left unimplemented as I didn't have time (like pysam's get_aligned_pairs format for the alignment). There isn't support for tags which I think is what you want for "HP values", value of haplotype tag I'm guessing? I might circle back to that or bite the bullet and figure out how to implement the modified base stuff into pysam.

**Comment by rrazaghi** [comment]
perfect! Thank you so much! this is very useful

**Comment by rrazaghi** [comment]
I have a quick question about multithreading with modbampy. do you expect any sort of memory leak there?
I have done a simple test with ray library below between fetching bam in pysam and modbampy:

```python
import pysam
from modbampy import ModBam
import ray

@ray.remote
def test_modbam(bam, chrom, start, end):
    i = 0
    with ModBam(bam, chrom, start, end) as b:
        for read in b.reads():
            i += 1
    return i

@ray.remote
def test_pysam(bam, chrom, start, end):
    i = 0
    with pysam.AlignmentFile(bam, "rb") as b:
        for read in b.fetch(chrom, start, end):
            i += 1
    return i

ray.init(num_cpus=64)

result_ids = []
for i in range(10000):
    result_ids.append(test_pysam.remote(bam, chrom, start, end))
results = ray.get(result_ids)
    
result_ids = []
for i in range(10000):
    result_ids.append(test_modbam.remote(bam, chrom, start, end))
results = ray.get(result_ids)

ray.shutdown()
```
With pysam I don't see any memory usage increase (stays around 2GB). however, with modbampy the memory keeps increasing (with 10000 tasks up to 30-50Gb). I'm working on a big mem cluster so the job is finished but I worry if other users will have issues.
I completely understand that this is probably way outside the scope of what you wanted to achieve with modbampy, but I figured I'd ask for your input before investigating further.

Thanks a lot again for this great work!

**Comment by cjw85** [comment]
Hmm, thats a puzzle.

I run automated tests (with valgrind) to check for memory leaks in the C code responsible for doing the heavy lifting. The CFFI code on the Python side doesn't do too much, but might be responsible. Alternatively the Python is using C functions that have been specialised for use in the modbam2bed program. They might be memory hogs for how they are called from Python, I will have a think.

**Comment by rrazaghi** [comment]
Hi Chris,

I got a chance today to look a bit deeper into this.
seems like adding ffi.release to the exit function inside the ModBam class at least reduces the memory leak (does not eliminate) which is a bit weird since the ffi.gc should call the destructor automatically:

```python
def __exit__(self, type, value, traceback):
        """Exit context."""
        ffi.release(self._data)
        ffi.release(self._mod_state)
        pass
```

after playing around and trying to profile memory, my guess is the memory leak happens at this line:
https://github.com/epi2me-labs/modbam2bed/blob/c1dd39d69dff7f8b95de081e7e87bca1184c30b8/modbampy/__init__.py#L71

Do you have an insight as to how we can fix this?


btw for profiling memory I've been able to reproduce the leak just by calling ModBam in a for loop on a single thread:

```python
%%filprofile
i =0
chrom="chr20"; start=58851000; end=58856000
bam = "test_meg.bam"
for c in range(20):
    with ModBam(bam, chrom, start, end) as b:
        for read in b.reads():
            i+=1
```

**Comment by rrazaghi** [comment]
Hi @cjw85 ! Just checking in to see if you have any insight on this.

Thanks a lot!

**Comment by cjw85** [comment]
I've been meaning to come back to this but have been busy with other things. I'd need to think more, at a surface level the python code is almost a direct translation of the C code only using CFFI for some of the allocations.

**Comment by rrazaghi** [comment]
Thanks Chris!
I may have found a workaround using multiprocessing. If I feed certain chunks of regions into a processing pool and make sure to do pool.close() before processing the next batch then all the garbage is collected. Not a definite solution and It definitely makes it slower and memory consumption fluctuates between consecutive pools but this way I keep the peak memory under 3G on 64 threads.

**Comment by cjw85** [comment]
Hi @rrazaghi,

I cannot reproduce this error on either Linux or macOS using the following program:

```
import sys
from modbampy import ModBam

bam = sys.argv[1]
reg = sys.argv[2]
chrom, coords = reg.split(":")
start, end = (int(x) for x in coords.split("-"))

i = 0
for c in range(20):
    with ModBam(bam, chrom, start, end) as b:
        for read in b.reads():
            i+=1
            if i % 10000 == 0:
                print(f"Processed {i} reads")
            for r in read.mod_sites:
                print(".", end="")

```

After processing 500k reads the memory use is minimal.

**Comment by rrazaghi** [comment]
Hi @cjw85,

Thanks a lot for following up on this. I think I perhaps provided a small example that didn't fully capture memory usage. I just tried a few things that I share below:

1. I ran your script as is with mprof and below is the plot:
![image](https://user-images.githubusercontent.com/15005600/155009427-3b73dd41-2368-4e1e-970a-6b4973319490.png)
not totally showcasing but memory is slowly increasing!
2. I tried your script this time with range of 100 instead of 20:
![image](https://user-images.githubusercontent.com/15005600/155009588-18110142-248b-40e4-81fa-a410efe85f9a.png)
Now it seems to be a bit clearer I think
3. I think this really becomes an issue if processing a large number of regions. Below I share a simplified multiprocessing code that I tried:
```python
import sys
from modbampy import *
from multiprocessing import cpu_count, get_context, Pool
from itertools import repeat

def process_region(bam, region):
    i = 0
    chrom = region[0]
    start = int(region[1])
    end = int(region[2])
    with ModBam(bam, chrom, start, end) as b:
        for read in b.reads():
            i += 1
            
    return i

def process_bed(bam, bed, threads):
    
    data = []
    with open(bed,'r') as f:
        for line in f:
            bed_line = line.strip().split("\t")
            if bed_line[0] =="chr":
                continue
            data.append(bed_line)
            
    results = []
    p = Pool(threads)
    s = p.starmap(process_region, zip(repeat(bam), data))
    results.extend(s)
    p.close()
    p.join()
    
    print(len(results), "regions were processed!")
    
bam = sys.argv[1]
bed = sys.argv[2]
threads = int(sys.argv[3])

process_bed(bam, bed, threads)
```

I tried this on a bed file containing 70k regions and used 64 threads and the mprof looks like this:
![image](https://user-images.githubusercontent.com/15005600/155010060-adf20f57-d727-46e2-90b5-f53f5349ce2d.png)

Overall, I see a constant increase in memory usage. I tried this on another linux server but saw similar results.
I'd appreciate it if you could confirm the reproducibility of these on your end (Otherwise this prob means this is an issue on my side).

I'd also note the amount of increase in memory usage also depends on two other factors:
1. the window lengths (much smaller footprinting for enhancers for example)
2. the read lengths (I am mainly using ultra-long reads which might amplify any small memory issue)

Thank you again, Chris!

**Comment by cjw85** [comment]
Thanks for the feedback, with this I would suspect the issue then is with the ModBam class rather than the ModRead class, and so not something to do with parsing records per se, but accesses to the file. I need to check the htslib API, but the fact nothing is done to cleanup the `bam1_t *` pointer is suspicious.

**Comment by cjw85** [comment]
I managed to reproduce a slow memory increase with modbampy (I think I wasn't looking closely enough before because you mentioned 30-50Gb:
![image](https://user-images.githubusercontent.com/3592009/155155398-81079462-e6c9-49ba-8a5b-fe5f4ab1ed11.png)

Creating the I think the issue is in the creation of the `bam1_t*`. This shouldn't be a bare alloc (which is what I believe `ffi.new`, but rather also zero the memory: [sam.c#L409](https://github.com/samtools/htslib/blob/develop/sam.c#L409).

This fix is fairly straightforward therefore: use `bam_init1()` and `bam_destroy1()` in the `__init__()` and `__del__`.

This changes my memory use for your script from (running all 1000 base regions of chr20):
![image](https://user-images.githubusercontent.com/3592009/155169524-9e7a7087-06e0-4f02-aa53-b55b997a9aff.png)

to:
![image](https://user-images.githubusercontent.com/3592009/155169592-239059c9-3b34-4184-b5b4-0523119adbc1.png)

**Comment by cjw85** [comment]
Hi @rrazaghi, can you try using v0.4.6 and see how you get on?

**Comment by rrazaghi** [comment]
Hi @cjw85, 
Awesome! I just tested on enhancer and gene body regions genome-wide without any memory issues.

Thanks so much for fixing this!
