### ISSUE TITLE
How to modified the value in pos_mod

### ISSUE THREAD

**Issue by JeremyQuo** [epi2me-labs/modbam2bed#30]
for pos_mod in read.mod_sites:
     print(*)

I will change some information in pos_mod and save it.Can I?

**Comment by cjw85** [comment]
The Python API is intended for read only. Amending information in the BAM file is not supported.

**Comment by JeremyQuo** [comment]
Thanks for your answer. Another question is about megalodon, which can generate a mod_mapping.bam after running.
I wanna know how it decides the threshold or just default 0.33/0.66 to generate the final modified_base_xx.bed file.

**Comment by cjw85** [comment]
Please open an issue on the megalodon issues page to ask questions about megalodon.
