### ISSUE TITLE
how to deal with many bam files

### ISSUE THREAD

**Issue by Aline-Git** [epi2me-labs/modbam2bed#31]
Hello,

Thanks for this very useful tool !

I should I proceed if I have many (e.g. 308) bam files ? It will be complicated to put them all in a command line. Should I merge them first ?

Aline

**Comment by cjw85** [comment]
Running a `samtools merge` will be notionally equivalent to providing `modbam2bed` all of the files at once. Take your pick! 😄

**Comment by Aline-Git** [comment]
Thanks, it should be fast to choose :)
