### ISSUE TITLE
How to interpret 0-255 methylation score

### ISSUE THREAD

**Issue by marcpaga** [epi2me-labs/modbam2bed#32]
Thanks for providing a python implementation of the tool, this is very useful. We were working on methylation calls using megalodon, but since Guppy can do methylation calling now as well we are trying to use those. Following #2 has been very useful. 

Now I was wondering, how to translate the methylation scores as methylation probabilities? Is it as simple as 0 = 0% methylation prob and 255 = 100% methylation prob. And everything in between follows a linear scale? So to translate scores to probabilities -> score/255. I understand that perhaps, model outputs cannot be directly translated to probabilities, but we are used to use >0.6 as threshold in megalodon to call a methylation.

**Comment by cjw85** [comment]
This is detailed in the SAM spec: https://samtools.github.io/hts-specs/SAMtags.pdf:

> The continuous probability range 0.0 to 1.0 is remapped in equal sized portions
to the discrete integers 0 to 255 inclusively. Thus the probability range corresponding to integer value
N is N/256 to (N + 1)/256.

**Comment by marcpaga** [comment]
Excellent, thanks!
