### ISSUE TITLE
`modbam2bed` with or without `--aggregate`?

### ISSUE THREAD

**Issue by PanZiwei** [epi2me-labs/modbam2bed#35]
Hi,
I found the results are quite different between the `modbam2bed` with or without `--aggregate`. For the same merged bam outputs of Guppy, I got 546415624 sites with `modbam2bed --aggregate` function while only 27621326 sites with`modbam2bed`.

What's the `--aggregate` function for? What's the difference between `modbam2bed --aggregate  -p $prefix -e -m 5mC --cpg -t 4 -r chr20 $reference_genome $data_folder/*.bam > $bedmethyl` and `modbam2bed -p $prefix -e -m 5mC --cpg -t 4 -r chr20 $reference_genome $data_folder/*.bam > $bedmethyl`? 

If I am interested in the per-site information and am using modbam2bed to aggregate the modified base of Guppy results into the per-site level, should I use `modbam2bed` with or without `--aggregate`?

Also, I got some `nan` value in column 11 in both `modbam2bed --aggregate` and `modbam2bed`, is it expected? If so, does modbam2bed consider removing the nan rows in the future?

Thank you!

**Comment by cjw85** [comment]
From the CLI help:

```
      --aggregate            Output additional aggregated (across strand)
                             counts, requires --cpg or --chg.
```

The aggregated output combines base counts across strands into a single total. So for CpG methylation counts of bases at position `i` on the `+`-strand and position `i+1` on the `-`-strand are summed into a single record. This is where you have approximately half the number of rows in your aggregated output.

The appearance of `nan` in some output entries is deliberate and will not be changed. Removing these entries would constitute a loss of data and ambiguity; keeping them is explicit. There presence indicates reads spanned a locus but there were invalid base counts. A completely absent row (i.e. a reference position corresponding to a CpG) indicates no reads spanned the locus.

See the table in the README for the precise definitions of the column values and why this naturally leads to some values being `nan`.
