### ISSUE TITLE
about CpG number in modbam2bed output

### ISSUE THREAD

**Issue by kaanokay** [epi2me-labs/modbam2bed#37]
Hi,

When I run modbam2bed for CpGs, does the output has all CpGs in the genome or only those CpGs that have valid coverage. Namely, can I find all CpGs in a sample from modbam2bed output?

Bw.

**Comment by cjw85** [comment]
The code will output positions where there is at least one spanning reads, not every possible reference CpG.

**Comment by kaanokay** [comment]
Thank you.
