### ISSUE TITLE
Install modbam2bed via anaconda

### ISSUE THREAD

**Issue by ekushele** [epi2me-labs/modbam2bed#38]
Hi,

I want to add a container for modbam2bed in the (multi-package-containers)[https://github.com/BioContainers/multi-package-containers]

For this, I need to add modbam2bed to the [hash.tsv file](https://github.com/BioContainers/multi-package-containers/blob/master/combinations/hash.tsv) 
When I add modbam2bed, I'm getting the following error:

```
PackagesNotFoundError: The following packages are not available from current channels:
- modbam2bed
```

Adding `epi2melabs::modbam2bed` didn't help...

[This](https://github.com/BioContainers/multi-package-containers/issues/2389) is the issue I opened in the repo.

I would appreciate your assistance!

Thank you!

**Comment by cjw85** [comment]
Sorry,

We don't know anything about biocontainers. You're better off asking on biocontainers support channels.

**Comment by ekushele** [comment]
So I'll put it this way:
If I want to add modbam2bed as a package in a meta.yaml file, how can I do it?

**Comment by cjw85** [comment]
Please direct your question here:
https://github.com/BioContainers/multi-package-containers/issues
