### ISSUE TITLE
Using CRAM files is very slow (10x slower) if REF_CACHE is not configured beforehand

### ISSUE THREAD

**Issue by Coppini** [epi2me-labs/modbam2bed#39]
I've tried running modbam2bed using CRAM files as input and found that it generates the exact same output as using a BAM file, though the performance is MUCH worse.

I've tested this for two different samples, seeing the time go from 40:49 to  07:01:28 for one of them, and from 45:17 to 09:05:34 for the other (from around 40min to 7 or 9 hours).

That means that using CRAM files as input ends up taking 10× the time.

I tried piping the output from samtools, but modbam2bed only accepts files, not stdin in any way, so that didn't work. Process substitution (`modbam2bed ... <(samtools view ...)`) also didn't work since modbam2bed seems says "failed to read" (and that it expected an index).

Is there any way around this that avoids me having to convert from CRAM to BAM and store an intermediate file before running modbam2bed? Or is the only way first converting into BAM, then running modbam2bed on the "decompressed" BAM and deleting it afterwards?

Thank you!

**Comment by cjw85** [comment]
Hi @Coppini,

I don't believe we've observed this effect, we use modbam2bed in our [wf-human-variation](github.com/epi2me-labs/wf-human-variation) workflow with CRAM.

I would need to profile this to figure out exactly what's happening and if it can be made faster. Do you have a sample CRAM and reference I can use to investigate?

**Comment by cjw85** [comment]
@SamStudio8 Just reminded me of the importance of the REF_CACHE when using CRAM:
https://www.htslib.org/workflow/cram.html

For example, the workflow mentioned above takes care to export an environment variable to ensure the local copy of the reference is used: [methyl.nf#L11](https://github.com/epi2me-labs/wf-human-variation/blob/master/workflows/methyl.nf#L11).

**Comment by Coppini** [comment]
These were internal samples, but I'll try to reproduce it in some public data so that I can share.

Your comments on accessing references got me thinking though. Our reference is stored in a way that can make access to it slower. I didn't consider that since several other programs that access it seem to have the same runtime with both BAM and CRAM, so I assumed it wouldn't have an impact, but I'll try to run it again copying the reference to a local filesystem before starting modbam2bed.

I should have some data by tomorrow or Friday at the latest.

Thanks!

**Comment by SamStudio8** [comment]
It's more likely that htslib is not considering the location of your
reference at all, as using the reference file is the last resort. See this
from the page @cjw85 just shared, which is as true for htslib (used in
modbam2bed) as it is for samtools:

> By default Samtools checks the reference MD5 sums (“M5” auxiliary
> tag) in the directory pointed to by $REF_PATH environment variable (if it
> exists), falling back to querying the European Bioinformatics Institute
> (EBI) reference genome server, and further falling back to the @SQ “UR”
> field if these are not found.

You won't notice this problem with samtools so long as you provide
`--reference`, but if you wish to use other tools that rely on htslib
internally (such as modbam2bed) with CRAM, you should follow the best
practice on that page to build a REF_CACHE.

**Comment by Coppini** [comment]
The problem was indeed with `REF_CACHE`. 

I generated it in advance and the time modbam2bed takes to process CRAM files is now equal to the time it takes for BAM. 

Thank you!

I'm gonna mark this issue as completed, but feel free to unresolve it if you plan on implementing something for when `REF_CACHE` isn't set.
