### ISSUE TITLE
modbam2bed biowasm per read output

### ISSUE THREAD

**Issue by rrazaghi** [epi2me-labs/modbam2bed#4]
Hi Chris!

Inspired by webassembly, I was thinking of deploying my visualization tool using biowasm and Aioli. Initially, I wanted to use the pyodide project to run modbampy or pysam and compile python on webassembly but after spending some time it seems a bit hard to package these python packages with C extensions. So I was wondering if it's feasible to output per read data from the modbam2bed command line using aioli and then parse the output (either pure JS or using Pyodide simple parsing). I already have some plotly code for this that could easily be adopted.

Thanks!

**Comment by cjw85** [comment]
This could be implemented, though I wonder what extent its necessary (or useful). Running `samtools view` from biowasm will output the mod-base tags. Something implemented in modbam2bed would similarly be outputting text per read, albeit in a different form.

**Comment by rrazaghi** [comment]
Ah that's right! I forgot about that. I think samtools should be sufficient. Probably the only difference would be that I'd need to get the aligned pairs (query -> ref) from samtools view
