### ISSUE TITLE
Output Issues

### ISSUE THREAD

**Issue by jchan3188** [epi2me-labs/modbam2bed#41]
Hi, I'm not sure if this is working as intended, but modbam2bed doesn't seem to generate a BED file when I just want the default stranded output. The output goes to stdout. However if I do use other options such as --aggregate the the aggregate file is generated as expected. Outputting to stdout wouldn't necessarily be a problem, but that output also contains the "processing" text and for a file that contains a lot of CpGs, the text formatting becomes off after a while. Is this normal? Is there anyway to get the stranded output in regular BED format? 

Thank you

**Comment by cjw85** [comment]
Hello @jchan3188,

Can you provide a reproducible example?

**Comment by jchan3188** [comment]
Sorry, I was running modbam2bed with Slurm. I assumed the Slurm output file is the same as the standard output file. I decided to run a test and redirected the output with in my script to a file and that seemed to work. 

Thank you
