### ISSUE TITLE
ModuleNotFoundError: No module named 'libmodbampy'

### ISSUE THREAD

**Issue by rowanhowellGE** [epi2me-labs/modbam2bed#42]
Hi,

I am trying to compile some per read data from a modified BAM file, as described in https://github.com/epi2me-labs/modbam2bed/issues/2. When I run `from modbampy import ModBam` I get the error `ModuleNotFoundError: No module named 'libmodbampy'`. 

Any advice on how to resolve this?

Thanks

**Comment by cjw85** [comment]
Hi @rowanhowellGE,

Can you provide details of how you have tried to install the Python library?

**Comment by rowanhowellGE** [comment]
I have modbampy v 0.6.3 installed with pip.

**Comment by cjw85** [comment]
I do not know why you would receive this error. I do not believe it is a problem with the code, as all our internal CI tests are working and no other users have reported such an issue.

**Comment by keenhl** [comment]
I have modbampy v 0.9.5 installed with pip and am getting the same error.  I get the same error both with python 3.7 or python 3.8.
