### ISSUE TITLE
Question about HG002 data

### ISSUE THREAD

**Issue by PanZiwei** [epi2me-labs/modbam2bed#43]
Hi,

I was trying to utilize the ONT-released HG002 data (https://labs.epi2me.io/gm24385-5mc) and am wondering whether it is possible to ask several questions about the dataset itself.

1. What is the bisulfite sequencing method for NA24385/HG002? Is it Whole Genome Bisulfite Sequencing (WGBS) or reduced representation bisulfite sequencing (RRBS)?

2. For Nanopore sequencing, what is the specific pore version and device used?

**Comment by cjw85** [comment]
The bisulfite sequencing is whole genome, not RRBS.

The Nanopore sequencing was R9.4.1 flowcells run on GridION.
