### ISSUE TITLE
How to get mapped sites number from modbam file

### ISSUE THREAD

**Issue by PanZiwei** [epi2me-labs/modbam2bed#44]
Hi,
I am wondering if there is a way to calculate the number of 1)mapped sites and 2)unmapped sites aligned with the reference genome from modbam file to have an idea about the site coverage. Right now I believe I can only get the site number that are corresponding to a specific threshold.

Thank you!

**Comment by cjw85** [comment]
Hi @PanZiwei,

I'm not sure I understand your question. The output is deliberately designed to provide information on reads spanning a reference position regardless of being the reference base, a modified base related to the reference base, a substitution, or a deletion in the query sequence.

Please see the definitions and table in the README file.
