### ISSUE TITLE
`modbampy.ModBam.pileup` idiosyncrasies or inconsistencies

### ISSUE THREAD

**Issue by thekugelmeister** [epi2me-labs/modbam2bed#45]
When using `modbampy.ModBam.pileup` to aggregate counts from a Megalodon output BAM file (with `A+Y` modification tags), I am observing some inconsistencies with the results depending on what `mod_base` I request. I am also a bit confused by the documentation of return values from `pileup`. Therefore, I am unsure whether this requires a fix or a documentation update (or both).

In summary, when I ask for a pileup of counts corresponding to a base with modified data present, I get different values in the "usual DNA bases" columns of the `counts` results matrix compared to when I ask for a pileup of a different modification.

Here is a test script I created to demonstrate this:
```python
from modbampy import ModBam

# Arbitrary region known to contain 6mA in the test file
window = ('chr14', 44125008, 44125326)
# Arbitrary index found to contain 6mA
test_pos = 100

# Megalodon BAM output containing A+Y 6mA calls
with ModBam('/path/to/file.bam') as bam:
    pos_default, counts_default = bam.pileup(*window)
    pos_Y, counts_Y = bam.pileup(*window, mod_base='Y')
    pos_Z, counts_Z = bam.pileup(*window, mod_base='Z')

counts_labels = 'acgtACGTdDmMfF'
print('\t'.join(['label', 'default', 'Y', 'Z']))
for label, count_default, count_Y, count_Z in zip(counts_labels,
                                                  counts_default[test_pos],
                                                  counts_Y[test_pos],
                                                  counts_Z[test_pos]):
    print('\t'.join([f'{label}:', str(count_default), str(count_Y), str(count_Z)]))
```
This asks for three pileups with different `mod_base` settings: the default (which should be `"m"`, and not present), `"Y"` (which is present), and `"Z"` (which is not present).

Example results:
```
label   default Y       Z
a:      0       0       0
c:      0       0       0
g:      0       0       0
t:      0       7       0
A:      0       0       0
C:      0       0       0
G:      0       0       0
T:      11      11      11
d:      0       0       0
D:      0       0       0
m:      0       2       0
M:      0       0       0
f:      0       1       0
F:      0       0       0
```
Observations / Questions:
* In this example, there are reverse-strand `t` bases only present in the `Y` pileup, while the forward-strand counts remain consistent across all three pileups. Why should this be the case?
* Even though I am searching for 6mA modifications, the results here are counted as `T` bases. Given that the modifications in the `Y` pileup are listed as coming from the reverse strand, am I correct in extrapolating that "reverse-strand T bases" are more accurately described as "reverse-strand A bases that map to a T on the forward strand"?
* Tangential question: how would you go about calculating the proportion of modified bases at a particular position from the count vector for that position?

**Comment by cjw85** [comment]
Hi Jeremy,

I'm at a conference reading this on my phone. I need some time to digest this and reflect.

The recent release changed the logic for how counts are accumulated. Can you check the version of the library you are using? Also if you can provide an extract of the BAM for me to review that would be great.

Note the most recent version includes two extra columns for "uncalled" bases (refer to the SAM spec for the meaning of this, where it talks about `?` mod tags).

For your tangential question, the README shows the formulas which are used in the modbam2bed program. The program creates it's output from the same array which the Python API has access.

**Comment by thekugelmeister** [comment]
Sigh. Never post an issue without checking whether the package had been updated 2 days after you started working with it...

The results above were with version `0.6.3`. I upgraded to version `0.7.0` and updated my test script to include the new `canon_base` argument, which now appears to be required for non-standard modification codes (i.e. ones not specified in https://samtools.github.io/hts-specs/SAMtags.pdf). This seems to address most if not all of my concerns.

Updated script:
```python
from modbampy import ModBam

# Arbitrary region known to contain 6mA in the test file
window = ('chr14', 44125008, 44125326)
# Arbitrary index found to contain 6mA
test_pos = 100

# Megalodon BAM output containing A+Y 6mA calls
with ModBam('/path/to/file.bam') as bam:
    pos_default, counts_default = bam.pileup(*window)
    pos_Y, counts_Y = bam.pileup(*window, mod_base='Y', canon_base='A')
    pos_Z, counts_Z = bam.pileup(*window, mod_base='Z', canon_base='C')

counts_labels = 'acgtACGTdDmMfF'
print('\t'.join(['label', 'default', 'Y', 'Z']))
for label, count_default, count_Y, count_Z in zip(counts_labels,
                                                  counts_default[test_pos],
                                                  counts_Y[test_pos],
                                                  counts_Z[test_pos]):
    print('\t'.join([f'{label}:', str(count_default), str(count_Y), str(count_Z)]))
```

Output:
```
label   default Y       Z
a:      0       0       0
c:      0       0       0
g:      0       0       0
t:      10      7       10
A:      0       0       0
C:      0       0       0
G:      0       0       0
T:      11      11      11
d:      0       0       0
D:      0       0       0
m:      0       2       0
M:      0       0       0
f:      0       1       0
F:      0       0       0
```

A couple of minor observations:
* Documentation of the `canon_base` argument to `pileup` would be a good addition to the README
* The error for not using a standard modification type could be improved: ```ValueError: Modified base type '89' unknown. Please provide a value for 'base' to describe the unmodified base.``` Translating the ASCII code to a character and referencing the appropriate missing argument would avoid confusion.
* Making methods for calculating the values in the output table available in the python API could be useful for some users? They are simple to calculate, but it could help maintain consistency in users' results when using this package.

Thank you for your expedient reply! I'm glad that this wound up being a trivial issue (minus the effort involved in the `0.7.0` update of course).

**Comment by cjw85** [comment]
@thekugelmeister 

Are you content that the answers with v0.7.0 are now sane, or do you still want me to look at your data?

I'll work on the documentation and and add the additional derived fields to the Python output.

**Comment by thekugelmeister** [comment]
I am very content that the answers in v0.7.0 are self-consistent and sane. Thank you for checking back!

I have additional observations about the exact output values (as compared to those from our in-house tool, for example), but those require additional investigation and would be better covered by a separate issue if need be.
