### ISSUE TITLE
Working with Dorado Basecaller

### ISSUE THREAD

**Issue by ethan-mcq** [epi2me-labs/modbam2bed#46]
Does this tool only work with the Guppy basecaller? I used the Dorado basecaller like so:
```
@PG     ID:basecaller   PN:dorado       VN:0.1.1+eb48766        CL:dorado basecaller dorado-0.1.1/dna_r10.4.1_e8.2_400bps_hac@v4.0.0 fast5s --modified-bases 5mCG_5hmCG
```
I can't seem to get it to work, although the test data works just fine. Thanks for the help in advance!

**Comment by cjw85** [comment]
The program will work with any BAM file containing aligned reads and MM and ML tags.
