### ISSUE TITLE
Don't have reference fasta

### ISSUE THREAD

**Issue by keenhl** [epi2me-labs/modbam2bed#48]
What if I have bam files with the MM and ML tags,  but I don't have the reference fasta file?  Is the three any I can use modbam2bed or is there an alternative approach that doesn't need the reference file.

Thank you for your help

**Comment by cjw85** [comment]
The reference file is required to provide motif filtering (e.g. filtering to CpG loci).

Can you comment more on what you are trying to accomplish ultimately with your data. The intent of modbam2bed is to summarise modified base information with respect to reference coordinates. I would assume any analysis you might want to do with the resultant files would also require the reference sequence.

Is this perhaps a BAM file straight from Guppy/dorado without alignment information?

**Comment by keenhl** [comment]
Thanks for your help.  I have bam files from two samples.  In both, most of the reads map to a particular chromosomal region. I have already confirmed this. In one of the samples, there should be a high level of methylation whereas in the other sample there should be a low level of methylation.  This is what I am trying to do now.

**Comment by cjw85** [comment]
I'm now confused. You say most reads map to a particular chromosomal region. So it sounds like you must have a some point in time had a reference file?

**Comment by keenhl** [comment]
I didn't create the bam files.  I agree with you. I assume the person that created the bam files must have had a reference file.

**Comment by cjw85** [comment]
The next release of modbam2bed will make the reference file optional. But this will mean that functionality like motif filtering will be disabled when a reference is not provided.

I would advise tracking down your reference file.

**Comment by keenhl** [comment]
Thanks.  I don't have access to the original reference file, but I used the header information from the bam files to identify the likely reference that was used.  I ran modbam2bed using that file, and it seems to have worked.  I will close this issue now.  Thanks again for your help.
