### ISSUE TITLE
error while loading shared libraries: libhts.so.3

### ISSUE THREAD

**Issue by palakela** [epi2me-labs/modbam2bed#49]
Hi, 

I am trying to install `modbam2bed` in a conda environment using Linux CentOS 8.

I have used the following command, and the environment has been created: `conda create -n modbam2bed -c bioconda -c conda-forge -c epi2melabs modbam2bed`.

Then trying running `modbam2bed --help` I get this error: `modbam2bed: error while loading shared libraries: libhts.so.3: cannot open shared object file: No such file or directory`.

I have understood I am missing the correct version of  `libhts`, and I have tryed to install it, but I am not able to solve the issue, could please someone help me?

**Comment by cjw85** [comment]
Hi @palakela

In your conda environment, cna you please try to force the install of htslib 1.16. I've seen this before, where for whatever reason conda installs an incorrect htslib version and then things don't work correctly:

```
conda install -c conda-forge -c bioconda htslib==1.16
```

**Comment by palakela** [comment]
It worked, thanks!
