### ISSUE TITLE
Unexpected behavior calling `list()` on `ModBam().reads()` generator

### ISSUE THREAD

**Issue by thekugelmeister** [epi2me-labs/modbam2bed#50]
When iterating through a `ModBam().reads()` generator, things appear to work as expected. However, when calling `list()` on that generator to load a set of reads into memory for more complex processing, every entry in the resulting list has the same values.

I created a tiny test BAM file (attached) with 4 reads, 10bp each, in which only the last read exhibits methylation. The corresponding SAM file is
```
@HD	VN:1.4	SO:coordinate
@SQ	SN:ref	LN:100
r001	0	ref	1	30	10M	*	0	10	GGGGGGGGGG	*
r002	0	ref	1	30	10M	*	0	10	AAAAAAAAAA	*
r003	0	ref	1	30	10M	*	0	10	AAAAAAAAAA	*
r004	0	ref	1	30	10M	*	0	10	AAAAAAAAAA	*	Mm:Z:A+Y,0,0,0,0,0,0,0,0,0,0;	Ml:B:C,255,255,255,255,255,255,255,255,255,255
```

Running the file `modbam_generator_bug.py` (attached) yields the following output:
```
n reads: 4
read addresses: ['0x7fd732c0b950', '0x7fd732c1a550', '0x7fd7310ba810', '0x7fd7310ba850']

read names: ['r004', 'r004', 'r004', 'r004']
n mod sites per read: [10, 10, 10, 10]
```

There are 4 reads as expected, each of which is stored at a different memory address. However, the names and number of mod sites reported for each of these objects are always the values for the last read in the file.

I presume this is somehow the result of aggressive garbage collection? Is there any way to change this behavior without drastically impacting performance?

[test.zip](https://github.com/epi2me-labs/modbam2bed/files/10819290/test.zip)

**Comment by cjw85** [comment]
This is the expected behaviour. The Python iterator is simply a proxy to a read iterator in htslib. Creating a Python list is creating a list with multiple entries of a single C pointer. By the time the Python iterator is exhausted this pointer points to the last read.

The API could be changed to make a copy of every record it reads from BAM. This would sacrifice performance, though it is what pysam does. Is there a particular reason you need to have all records available simultaneously?

**Comment by thekugelmeister** [comment]
Okay! I'm glad to know this behavior was expected. Being used to `pysam`, I was surprised to see that this is how it works. It makes sense that this design decision would improve performance, and for most use cases should be perfectly fine.

I came across this while doing some debugging, where I was attempting to compare results between different reads. I'm not sure whether that will be a common use case, and can generally be circumvented by doing some deep copying of return values if need be.

Adding some documentation about design decisions like this could be useful? As long as this is known and expected, I don't think it is a huge deal.

**Comment by cjw85** [comment]
Apologies for causing you to go on a goose chase. It don't know I would call it a design decision to behave like this, unless you count my laziness to adding the few lines of code to copy the data as a decision! Its easily changed. To be honest I'd expected pysam to have a better API for mod bases by now (it does have one by the way, but its perhaps a little clunkier than the one presented here).

**Comment by thekugelmeister** [comment]
Got it. I've just taken a look at your comments on the pysam repository; I agree it would be nice to have all of this completely integrated into pysam, since it's relying on the same underlying methods in htslib.

For our use case, the high speed pileup functionality of your package is especially attractive. As far as I understand it, this functionality has yet to be integrated into pysam, which is why we have been looking into modbampy instead. I guess time will tell where things end up.

**Comment by cjw85** [comment]
I have changed the behaviour of the API to make copies of all BAM structures during iteration. Its therefore now possible to create a list of alignments.
