### ISSUE TITLE
Symbol lookup error: undefined symbol: bam_mods_at_qpos

### ISSUE THREAD

**Issue by szakallasn3** [epi2me-labs/modbam2bed#52]
Hello everyone, 

I installed modbam2bed by: conda create -n modbam2bed -c bioconda -c conda-forge -c epi2melabs modbam2bed

however, when I try to run it with this command:  modbam2bed -e -m 5mC --cpg -t 4 -r chr20 $reference_genome $data_folder/*.bam > $bedmethyl

get the following error:  Symbol lookup error: undefined symbol: bam_mods_at_qpos

Does anyone faced with this or similar problem, or has any idea how to solve this? 

Thanks

**Comment by cjw85** [comment]
This is likely related to https://github.com/epi2me-labs/modbam2bed/issues/49.

There's been an issue recently with conda-forge updating some libraries, and that causing conda to install ancient versions of htslib.

Please try running:

```
conda install -c conda-forge -c bioconda htslib==1.16
```

**Comment by szakallasn3** [comment]
Thanks, this solved my problem.
