### ISSUE TITLE
`undefined symbol: inflate` for modbampy

### ISSUE THREAD

**Issue by PanZiwei** [epi2me-labs/modbam2bed#53]
Hi,
I encountered an error when using the modbampy. Would really appreciate it if you can provide any help. Thanks!

The package I am using:`python==3.6.13, modbampy==0.9.3, htslib==1.16``

```
Traceback (most recent call last):
  File "/modbam2bed.py", line 27, in <module>
    from modbampy import ModBam
  File "/Anaconda3/envs/modbam2bed/lib/python3.6/site-packages/modbampy/__init__.py", line 8, in <module>
    import libmodbampy
ImportError: /Anaconda3/envs/modbam2bed/lib/python3.6/site-packages/libmodbampy.abi3.so: undefined symbol: inflate
```

**Comment by cjw85** [comment]
Can you please provide full details and logs for how you have installed modbampy?

On [PyPI](https://pypi.org/project/modbampy/#files) we provide binary distributions for Python 3.7-3.10 only. Your log suggests you are using Python 3.6. Please use a more recent version of Python.

**Comment by PanZiwei** [comment]
Thanks for the quick response! I am guessing it might be a version issue.

Update: I switched to Python 3.9 and it worked this time. 
```
mamba create -n modbam2bed -c bioconda -c conda-forge -c epi2melabs modbam2bed python=3.9
```
