### ISSUE TITLE
version

### ISSUE THREAD

**Issue by rl4940** [epi2me-labs/modbam2bed#54]
I tried to download modbam2bed for multiple times and the version stays with 0.5.0. 
Does anyone knows what is going on with this issue?

code below:
mamba create -n modbam2bed -c bioconda -c conda-forge -c epi2melabs modbam2bed

This may be the potential error:
Looking for: ['modbam2bed']

warning  libmamba Could not parse state file: Could not load cache state: [json.exception.type_error.302] type must be string, but is null
warning  libmamba Could not parse state file: Could not load cache state: [json.exception.type_error.302] type must be string, but is null
warning  libmamba Could not parse state file: Could not load cache state: [json.exception.type_error.302] type must be string, but is null
warning  libmamba Could not parse state file: Could not load cache state: [json.exception.type_error.302] type must be string, but is null
warning  libmamba Could not parse state file: Could not load cache state: [json.exception.type_error.302] type must be string, but is null
warning  libmamba Could not parse state file: Could not load cache state: [json.exception.type_error.302] type must be string, but is null
warning  libmamba Could not parse state file: Could not load cache state: [json.exception.type_error.302] type must be string, but is null
warning  libmamba Could not parse state file: Could not load cache state: [json.exception.type_error.302] type must be string, but is null
epi2melabs/linux-64                                           No change
epi2melabs/noarch                                             No change
pkgs/r/linux-64                                      1.4MB @   2.0MB/s  0.4s
pkgs/r/noarch                                        1.3MB @   1.3MB/s  0.3s
bioconda/noarch                                      4.2MB @   3.8MB/s  1.2s
bioconda/linux-64                                    4.6MB @   3.7MB/s  1.4s
pkgs/main/noarch                                   820.3kB @ 502.6kB/s  0.5s
pkgs/main/linux-64                                   5.5MB @   2.6MB/s  1.1s
conda-forge/noarch                                  11.7MB @   4.5MB/s  2.8s
conda-forge/linux-64                                30.6MB @   5.1MB/s  6.4s
Transaction

**Comment by eld211** [comment]
I am having the same issue the only version I can get working in my conda environment is 0.5.0 and the --aggregate flag in this version doesn't appear to exist

**Comment by cjw85** [comment]
Various people have had issues recently after a change to some upstream pacakges in conda-forge and bioconda. Can you please trying running:

```
mamba create -n modbam2bed -c conda-forge -c bioconda -c epi2melabs htslib==1.16 modbam2bed==0.9.4
```

and report the list of packages that are installed.

**Comment by cjw85** [comment]
In addition, @rl4940 your errors suggest you have broader issues with your mamba installation. I've never seen those warnings before.

**Comment by rl4940** [comment]
Yes It works with this code:
```
mamba create -n modbam2bed -c conda-forge -c bioconda -c epi2melabs htslib==1.16 modbam2bed==0.9.4
```
Thank you very much!
And the mamba seems good in this case for me.
