### ISSUE TITLE
Is there a way to mimic the "edge_filter" behavior of megalodon in modbam2bed?

### ISSUE THREAD

**Issue by billytcl** [epi2me-labs/modbam2bed#55]
Megalodon has a feature called "edge_filter" (https://nanoporetech.github.io/megalodon/advanced_arguments.html?highlight=edge):

```
--edge-buffer

Do not process sequence variant or modified base calls near edge of read mapping.

Default: 30
```

This is useful in some niche applications for us. Is there a way that modbam2bed can do this, or would I have to manually cobble something together using modbampy?

**Comment by cjw85** [comment]
You would have to pre-trim the alignments, or use the Python interface.

**Comment by billytcl** [comment]
Rats! I was hoping there would be an easier way. Thanks for the quick reply!
