### ISSUE TITLE
how is coverage calculated

### ISSUE THREAD

**Issue by xiaoyunguo** [epi2me-labs/modbam2bed#56]
Hello, 
I ran modbam2bed on Nanopore sequencing data. In the output file, I've seen entries like the following that has nonzero coverage, but number of methylated, unmethylated and ambiguous calls are all 0. basically they don't add up to the coverage, and the methylation is "nan". I wonder what I am seeing here. 
Note: Not all columns from the output file are shown here and I added the column name to make it easier to read
```
chr     start   end     me_type  score  strand  coverage        percent_me      n_unmeth         n_me   n_between_threshold
6       170865322       170865323       5mC     0       -       14      nan     0       0       0
6       170865321       170865322       5mC     0       +       0       nan     0       0       0
6       170865188       170865189       5mC     0       -       16      nan     0       0       0
6       170865187       170865188       5mC     0       +       0       nan     0       0       0
```
Most other entries in the output are as expected
```
chr     start   end     me_type  score  strand  coverage        percent_me      n_unmeth         n_me   n_between_threshold
1       104     105     5mC     1000    +       8       100.00  0       8       0
1       105     106     5mC     1000    -       6       100.00  0       6       0
1       113     114     5mC     1000    +       8       100.00  0       8       0
```

Thanks so much!

**Comment by cjw85** [comment]
Definitions are given in the [README](https://github.com/epi2me-labs/modbam2bed#method-and-output-format).
