### ISSUE TITLE
Removal of setting canonical and mod thresholds

### ISSUE THREAD

**Issue by pwh124** [epi2me-labs/modbam2bed#57]
Why are the settings that allow for canonical and modified thresholds being removed?

I think this is a great feature and allows for one to set thresholds like "non-meth < 0.2 and meth > 0.8" which allows for ambiguous calls to be ignored. 

With the new `--threshold` argument, how would I parse a modbam to produce something giving me "non-meth < 0.2 and meth > 0.8?"

**Comment by cjw85** [comment]
`modbam2bed` is now deprecated. Please use [modkit](https://github.com/nanoporetech/modkit).
