### ISSUE TITLE
modbampy

### ISSUE THREAD

**Issue by keenhl** [epi2me-labs/modbam2bed#59]
Thank for the for the prompt response.  Here is the readme.  I have did everything there and have tried multiple combinations of python and modbampy and I can't get anything to work.  

Python package

A Python package is available on [PyPI](https://pypi.org/project/modbampy/) which contains basic functionality for parsing BAM files with modified-base information. It is envisaged that this will eventually be replaced by an implementation in [pysam](https://pysam.readthedocs.io/en/latest/index.html). As such the interface is supplements but does not integrate or replace pysam.

The package can be installed with:

pip install modbampy
The package contains simply to modes of use. Firstly an interface to iterate over reads in a BAM file and report modification sites:

from modbampy import ModBam
with ModBam(args.bam) as bam:
    for read in bam.reads(args.chrom, args.start, args.end):
        for pos_mod in read.mod_sites:
            print(*pos_mod)

**Comment by cjw85** [comment]
This project is now deprecated and will not be supported, please see the README for further details.

**Comment by keenhl** [comment]
The readme doesn't provide any further details. That's what I'm trying to tell you
