### ISSUE TITLE
Feature request - outfile

### ISSUE THREAD

**Issue by colindaven** [epi2me-labs/modbam2bed#6]
Hi,
thanks for this simplified tool, really appreciate it.

Could you please add a `-o outfile` option for use in pipelines in future (for some reason it's crashing on output redirection with > for me here) ? That would be great.

Thanks.

**Comment by cjw85** [comment]
Can you provide details of what exactly is happening when you try to redirect the output? I see no reason why this should be the case, certainly not that would be resolved by outputting to a different file stream than stdout. As such your error could reflect a wider issues.

**Comment by colindaven** [comment]
I think you're right, I'm just calling it incorrectly via a variable in a bash script.

```

modbam2bed/test_data$ bash test.sh
Analysing: 5-methylcytosine (5mC, C>m)
Fetched ecoli1, 4773681 4773681
Processing: ecoli1:0-4773681
100 %
Fetched ecoli2, 121807 121807
Processing: ecoli2:0-121807
100 %
Total time: 0.287770s
Analysing: 5-methylcytosine (5mC, C>m)
Fetched ecoli1, 4773681 4773681
Processing: ecoli1:0-4773681
[E::hts_open_format] Failed to open file ">" : No such file or directory
test.sh: line 9: 2691757 Segmentation fault      (core dumped) $cmd

## The script

(modbam2bed) rcug@hpc-rc08:/mnt/ngsnfs/tools/modbam2bed/test_data$ cat test.sh
#!/bin/bash


# redirect works
modbam2bed -m 5mC -t 16 ecoli.fasta 400ecoli.bam > out.txt

# redirect fails with segfault
cmd="modbam2bed -m 5mC -t 16 ecoli.fasta 400ecoli.bam > out.txt"
$cmd

```


Thanks, I'll close
