### ISSUE TITLE
Correct workflow for extracting modified bases from bonito calls 

### ISSUE THREAD

**Issue by jorisbalc** [epi2me-labs/modbam2bed#60]
Hello,

It seems I'm having some trouble extracting modified base percentages from bonito basecalls acquired through custom remora models. If I'm not mistaken the modbam2bed does not support custom modifications, only the ones from the `mod_base=` list. Is there a way around this? The remora models as I understand have specific tags for the modified bases in question, which would be called in the .bam. The only way I managed to get something out of it is with `modC --cpg` . However I presume this does not filter the modifications at all and simply differentiates canonical bases from modified ones as shown by "modC" in the .bed file. Is there some more accurate way of extracting custom modifications?

Any help is appreciated :)

**Comment by cjw85** [comment]
This project is now deprecated and support is no longer provided. Please see the README for further information.
