### ISSUE TITLE
visualize in IGV

### ISSUE THREAD

**Issue by sujunhao** [epi2me-labs/modbam2bed#62]
Thank you for creating this tool. I am currently trying to visualize the "bedMethyl" file generated from modbam2bed in IGV version 2.13.2.

However, when I try to load the file into IGV, I encounter an error message that says, "Error loading .... Error parsing line: chr20 60008 5mc 1000 + ....", I am wondering how I can resolve this problem.

Thanks in advance for your assistance.

JH

**Comment by cjw85** [comment]
modbam2bed is deprecated, please use: https://github.com/nanoporetech/modkit/
