### ISSUE TITLE
Diffrent output size for different insert bams?

### ISSUE THREAD

**Issue by assafgrw** [epi2me-labs/modbam2bed#64]
Hi,

As far as I understand the output should include data for each CpG in the genome regardless of the coverage (as there are rows with score of 0 at column 11). If that so, how come I get different outputs rows for different bam files?

**Comment by cjw85** [comment]
As noted at the top of the [README](https://github.com/epi2me-labs/modbam2bed), modbam2bed is deprecated. Please use [modkit](https://github.com/nanoporetech/modkit/).
