### ISSUE TITLE
Warning message inquiry

### ISSUE THREAD

**Issue by nsgarcia27** [epi2me-labs/modbam2bed#65]
Hi. I recently ran modbam2bed on a methylation bam file called with 6mA model. When I ran the command, it gave warning message:
```
modbam2bed --mod_base 6mA Azotobacter_vinelandii.fasta Azotobacter_vinelandii_sorted.bam > Azotobacter_vinelandii_6mA.bed
WARNING: You have specified either 5mC or 5hmC as a modified base.
         Oxford Nanopore Basecallers jointly call C, 5mC, and 5hmC. If you
         wish to combine calls of these bases into a single 'modified'
         count, please use the `--combine` option. The default behaviour
         is that calls of alternative modified bases are added to the
         alternatively-modified count.Analysing: 6-methyladenine (6mA, A>a)
```
It seems like it is saying I specified 5mC/5hmC, even though in the command, I obviously had `--mod_base 6mA` parameter. The run completed nonetheless and looks like the bed file result contains the 6mA methylation information. However, I am not sure how much I can trust this result given the warning message given.

**Comment by cjw85** [comment]
This project is now deprecated and you should instead use [modkit](https://github.com/nanoporetech/modkit/).
