### ISSUE TITLE
ERROR: --highthreshold must be larger than --lowthreshold

### ISSUE THREAD

**Issue by Baix7** [epi2me-labs/modbam2bed#67]
Hi, I am using modbam2bed with bam files basecalled by dorado,
`
modelpath="/path/to/model/dna_r10.4.1_e8.2_400bps_hac@v4.2.0"
model="/path/to/model/dna_r10.4.1_e8.2_400bps_hac@v4.2.0_5mCG_5hmCG@v2"

$doradoDir basecaller  $modelpath $pod5Dir --modified-bases-models $model --reference $reference --emit-moves > call.bam
modbam2bed -e -m 5mC --cpg -t 10 ref.fasta call.bam > cpg.bed
`

The commands above ran successfully. However, when I ran the command below to call the chg sites, an error came out,
`
modbam2bed -e -m 5hmC --chg -t 10 ref.fasta call.bam > chg.bed

ERROR: --highthreshold must be larger than --lowthreshold
`
How could I call chg/chh methylbed? Thank you!

**Comment by cjw85** [comment]
modbam2bed is deprecated l, please see README for further details.
