### ISSUE TITLE
Adding --aggregate flag does not result in aggregate behavior

### ISSUE THREAD

**Issue by ddubocan** [epi2me-labs/modbam2bed#68]
Hi,

When I use the aggregate flag, the output does not seem to be aggregated properly.
For example: 

```
chr1    591333  591334  5mC     1000    +       591333  591334  0,0,0   2       100.00
chr1    591334  591335  5mC     857     -       591334  591335  0,0,0   7       83.33
```

These 2 intervals originate from a singular CpG site, they should be one aggregate interval instead of 2 separate ones.
The command used to generate:  `modbam2bed -t 30 --cpg --aggregate -f 0.8 -m 5mC `

**Comment by cjw85** [comment]
modbam2bed is deprecated, no support will be undertaken. Please see the README for further information.
