### ISSUE TITLE
modbam2bed N_filt 

### ISSUE THREAD

**Issue by Houssem-der** [epi2me-labs/modbam2bed#70]
Hi everyone,
Just a quick question, when using the extended output of modbam2bed, is N_filt (column 14) considered as no modification?

Thank you.

**Comment by cjw85** [comment]
No. It is considered as ambiguous and not used in the calculation of modification frequency.

**Comment by liuqianhn** [comment]
@cjw85 Could you please explain more about what causes "ambiguous modification calling" or which situations "ambiguous modification calling" happened? Thank you.

**Comment by cjw85** [comment]
This is detailed in the README:

> Call filtering
> To determine the base present at a locus in a read, the query base in the BAM record is examined along with the modified base information. A "canonical" base probability is calculated as 1 - sum(P_mod), with P_mod being the set of probabilities associated with all the modifications enumerated in the BAM record. The base form with largest probability is taken as the base present subject to the user-specified threshold. If the probability is below the threshold the call is masked and contributes to the "filtered" base count rather than the "canonical" or "modified" counts.

You will note that the README also states:

We have a new bioinformatic resource that replaces the functionality of this project! See our new repository here: [modkit](https://github.com/nanoporetech/modkit/).

This repository is now unsupported and we do not recommend its use. Please contact Oxford Nanopore: [support@nanoporetech.com](mailto:support@nanoporetech.com) for help with your application if it is not possible to upgrade.
