### ISSUE TITLE
Methylation bed file output cols - Coming as 18 , description available only for 16 in readme

### ISSUE THREAD

**Issue by snehaleela** [epi2me-labs/modbam2bed#71]
Below is the output coming from the command:
modkit pileup --cpg --threads 16 --ref GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna sample.cram sample.cpg.bed

![image (1)](https://github.com/epi2me-labs/modbam2bed/assets/18367797/466f28d4-d878-413f-89cd-4b13eb82323d)

Even considering the "Included in extended output only".. There are still 2 more cols which we dont have the description for.

Can you guys tell us where these 2 cols description or any issue in the generation.

**Comment by cjw85** [comment]
This repository is now unsupported and we do not recommend its use. Please contact Oxford Nanopore: [support@nanoporetech.com](mailto:support@nanoporetech.com) for help with your application if it is not possible to upgrade.

We have a new bioinformatic resource that replaces the functionality of this project! See our new repository here: [modkit](https://github.com/nanoporetech/modkit/).
