### ISSUE TITLE
No module named libmodbampy

### ISSUE THREAD

**Issue by HJeffery** [epi2me-labs/modbam2bed#8]
When trying to use the python package there is an issue with not being able to find libmodbampy. 

Python program was installed by `pip install modbampy` with python 3.10.2.

**Comment by cjw85** [comment]
I suspect this is because PyPI has only wheels for Python 3.6-3.8 inclusive, and there is something broken about the source distribution on PyPI.

**Comment by HJeffery** [comment]
Thank you very much, python 3.8 seems to work.

**Comment by keenhl** [comment]
For me, with python Python 3.8.16, doesn't work.

ModuleNotFoundError: No module named 'libmodbampy'

**Comment by jnesme** [comment]
Same issue for me with python 3.8.16
